version: "3"

services:
  postgres:
    image: "postgres:latest"
  redis:
    image: "redis:latest"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./server:$HOME/app/"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - "5000:5000"
  
  client: 
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - "/app/node_modules"
      - "./client:$HOME/app/"
    ports:
      - "3000:3000"
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./worker:$HOME/app/"
